# Simple workflow for running static code analysis on GitHub Pages
name: Run static code analysis

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single sast job
  sast:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get -y install clang clang-tidy cppcheck 

      - name: Install CodeChecker
        run: sudo pipx install CodeChecker --force
 
      - name: Run sast
        run: ./Scripts/Sast/RunSast.sh

      # Upload sast artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: SastArtifacts
          path: ./Sast
